version: "3.8"

services:
  cs-techpinoy-net:
    image: jnonymous420/cs-techpinoy-net:latest   # ğŸ” Use your Docker Hub image here
    ports:
      - "8083:8083"                     # Assuming app inside container uses port 3000
    container_name: cs-techpinoy-net
